//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassEffectInstalador.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassEffectInstalador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Startup_INT.pcc
        ///BIOA_CRD00_00_DSG_LOC_INT.pcc
        ///BIOA_CRD00_LOC_INT.pcc
        ///BIOA_END00_LOC_INT.pcc
        ///BIOA_END20_02_CIN_LOC_INT.pcc
        ///BIOA_END20_02_DSG_LOC_INT.pcc
        ///BIOA_END20_Bridge_CIN_LOC_INT.pcc
        ///BIOA_END70C_Bridge_CIN.pcc
        ///BIOA_END70C_Bridge_CIN_LOC_INT.pcc
        ///BIOA_END70D_Bridge_CIN_LOC_INT.pcc
        ///BIOA_END70_00_DSG_LOC_INT.pcc
        ///BIOA_END70_02BSuicide_CIN.pcc
        ///BIOA_END70_02B_DSG_LOC_INT.pcc
        ///BIOA_END70_02C_CIN.pcc
        ///BIOA_END70_02C_CIN_LOC_INT.pcc
        ///BIOA_END70_02C_DSG_LOC_INT.pcc
        ///BIOA_END70_02D_DSG_LOC_INT.pcc
        ///BIOA_ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ListPackageLE1 {
            get {
                return ResourceManager.GetString("ListPackageLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BIOGame_INT.tlk
        ///BioGame_Update_INT.tlk
        ///DLC_33_INT.tlk
        ///DLC_33_Test_INT.tlk
        ///DLC_10_INT.tlk
        ///DLC_10_Test_INT.tlk
        ///DLC_11_INT.tlk
        ///DLC_11_Test_INT.tlk
        ///DLC_34_INT.tlk
        ///DLC_34_Test_INT.tlk
        ///DLC_15_INT.tlk
        ///DLC_15_Test_INT.tlk
        ///DLC_21_INT.tlk
        ///DLC_21_Test_INT.tlk
        ///DLC_40_INT.tlk
        ///DLC_40_Test_INT.tlk
        ///DLC_24_INT.tlk
        ///DLC_24_Test_INT.tlk
        ///DLC_25_INT.tlk
        ///DLC_25_Test_INT.tlk
        ///DLC_3_INT.tlk
        ///DLC_3_Test_INT.tlk
        ///DLC_2_INT.tlk
        ///DLC_2_Test_INT.tlk
        ///DLC_12_INT.tlk
        ///DLC_12_Test_INT.tlk
        ///DLC_19_INT.tlk
        ///DLC_19_Test_INT [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ListTalkLE2 {
            get {
                return ResourceManager.GetString("ListTalkLE2", resourceCulture);
            }
        }
    }
}
